version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "MoonMoon1919/peyton"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building test Docker Image"
    type: "build"
    image_name: "MoonMoon1919/peyton"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    registry: "docker"
  run_all_checks:
    type: "parallel"
    stage: "test"
    steps:
      run_tests:
        title: "Run PyTest"
        image: "${{build}}"
        commands:
          - "make test"
        stage: "test"
      run_safety:
        title: "Run Safety"
        image: "${{build}}"
        commands:
          - "make check/safety"
      run_format_check:
        title: "Run Formatting Check"
        image: "${{build}}"
        commands:
          - "make check/format"
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "skip ci") == false'
  build_and_push_package:
    title: "Build package and push to CloudRepo"
    image: "${{build}}"
    environment:
      - REPOSITORY_URL=${{REPOSITORY_URL}}
      - REPOSITORY_USERNAME=${{REPOSITORY_USERNAME}}
      - REPOSITORY_PASSWORD=${{REPOSITORY_PASSWORD}}
    commands:
      - "make build/package"
      - "make upload/package"
    stage: "deploy"
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "no push") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'
